### ISSUE TITLE
Feature request: Base Image with JDK 9

### ISSUE THREAD

**Issue by DominikPieper** [fabric8io-images/java#21]
Could you add images with JDK 9 as base JDK/JRE?

**Comment by rhuss** [comment]
Good point. Actually we need to check whether the addons (Jolokia/Prometheus) currently work with Java 9 and if not, possibly disable them.

Also we should adapt the startup script to the new options for the Java 9 for better conformity to containers.

**Comment by pappnase99** [comment]
+1 for Java 10 also.

**Comment by rhuss** [comment]
Actually, we are planning for Java 11, I think it makes sense to skip Java 9 and Java 10.

'hope this is ok for you.
