### ISSUE TITLE
Request for new aarch64 branch

### ISSUE THREAD

**Issue by KurtStam** [fabric8io-images/java#3]
Hi Roland, can you please create a branch called 'aarch64'. I will maintain a version of the images for the aarch64 (armv8) architectures there. I will issue a PR as soon as the branch is created. 
For a sneak peak: 

https://github.com/KurtStam/java/tree/aarch64. 

https://hub.docker.com/r/project31/aarch64-fabric8-java-centos-openjdk7-jdk
https://hub.docker.com/r/project31/aarch64-fabric8-java-centos-openjdk7-jre
https://hub.docker.com/r/project31/aarch64-fabric8-java-centos-openjdk8-jdk
https://hub.docker.com/r/project31/aarch64-fabric8-java-centos-openjdk8-jre
https://hub.docker.com/r/project31/aarch64-fabric8-java-jboss-openjdk7-jdk
https://hub.docker.com/r/project31/aarch64-fabric8-java-jboss-openjdk8-jdk

Note that for now I'm not building the alpine images.

Thx --Kurt

**Comment by rhuss** [comment]
done

**Comment by rhuss** [comment]
You should have now write access, too.

**Comment by KurtStam** [comment]
Cool I create the PR, I don't think giving me write access worked though.

**Comment by KurtStam** [comment]
My bad, I had to accept the invite :)
