### ISSUE TITLE
Vulnerabilities fixes

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io-images/java#32]
It will be good to update the image with latest updates to fix the vulnerabilities that are shown with version 1.5.2

**Comment by rhuss** [comment]
Just updated the Java minor versions and did a resping of the image builds.

1.5.3 should be available soon, monitor e.g. https://hub.docker.com/r/fabric8/java-alpine-openjdk8-jdk/builds

**Comment by rhuss** [comment]
And just released 1.5.4 including an update to run-java.sh 1.3.0
