### ISSUE TITLE
Is there a docker image for fabric8/java-alpine-openjdk11-jdk published to docker hub ?

### ISSUE THREAD

**Issue by kyanamgoutham** [fabric8io-images/java#53]
I looked for fabric8/java-alpine-openjdk11-jdk in docker hub and I can't seem to find it. However I did find an image of centos flavor for jdk11 fabric8/java-centos-openjdk11-jdk.

Is there known issues jdk11 on alpine ?

**Comment by rhuss** [comment]
The PR introducing the alpine image has just been merged and no new release has been scheduled in the meantime. I hope I can make a new release until the weekend, including alpine.

**Comment by i-wilson** [comment]
@rhuss any updates on pushing the alpine tags? If that config is managed in code somewhere I'd be happy to help out.

**Comment by rhuss** [comment]
Apologies that I haven't pushed recently. I just updated all packages and created a 1.6.4 tag/release so that the Docker automated builds have been triggered. They should be finished soon.

**Comment by i-wilson** [comment]
Hey @rhuss, looks like it still didn't create the new images in Docker Hub. Is it still under /u/fabric8? Meaning https://hub.docker.com/r/fabric8/java-alpine-openjdk11-jdk would be an example.

**Comment by rhuss** [comment]
@i-wilson thanks for the heads up. It was just that the repository has not been created on Docker Hub :) So I did this and created 1.6.5 tag so that this release should show up soon at the URL you mentioned.

Sorry ...

**Comment by i-wilson** [comment]
No problem, thanks for building this out!

**Comment by rhuss** [comment]
👍
