### ISSUE TITLE
Any plan for a UBI based image ?

### ISSUE THREAD

**Issue by lbroudoux** [fabric8io-images/java#56]
Hi,

I was wondering if you're planning to integrate a Java image based on Red Hat Universal Base Image that can be freely used and redistributed ?

I see many drivers for that: 
* Base `ubi8-minimal` is particularly lightweight, so is an interesting alternative to alpine,
* No ubi8 for Java is freely usable nor redistributable in Red Hat containers (see [here](https://access.redhat.com/containers/#/product/5c180b28bed8bd75a2c29a63)),
* People will surely want to add the `run-java.sh` and Agent Bond layers,
* It will allow to have a community image based on UBI 8 with util stuffs and ready to enter Red Hat certification process on Operators.

What do you think?

**Comment by rhuss** [comment]
I'm totally open to even fully replace the existing e.g. centos base image and I also think the UBI images are a very good choice.

However, I have currently no spare cycles to work on this but would help to integrate a PR.

**Comment by lbroudoux** [comment]
Hi @rhuss,

Thanks for reply. I'm currently having this need for the project I'm working on. WIll be happy to send a PR once I'll have something working (expecting end of this week).

**Comment by rhuss** [comment]
Awesome. Please be sure to use fish-pepper to fan-out the various build files (no manually editing all the files).

**Comment by lbroudoux** [comment]
Hi @rhuss,

I've got a working image and digging into fish-pepper.

However, it seems that Agent Bond install URL (found here https://github.com/fabric8io/agent-bond/blob/master/fish-pepper/agent-bond/install.dck... and pointing to http://central.maven.org/) is no more reachable. I think we have to upgrade to https://repo.maven.apache.org/

So I think I'll send a PR on `agent-bond` too ;-)

**Comment by rhuss** [comment]
good point. Not sure btw, whether agent-bond is still a good idea. Probably it's just better to configure prometheus and jolokia independently (to avoid coupling release cycles). 

I thought agent-bond has been already kind of removed, but all of that was quite some time ago.

But that's anther story.

**Comment by lbroudoux** [comment]
Hum... ok.

I think I’ll push a first version based on agent-bond that uses fish-pepper templates for UBI too. 

Then it will be easy to switch to prom + jolokia for all images. Is it ok for you ?

**Comment by lbroudoux** [comment]
Just see that agent-bond repository is archived and in read-only mode. I cannot submit new PR anymore.

**Comment by lbroudoux** [comment]
Hi @rhuss,

just send the PR #57. As a workaround for `agent-bond` being in archived mode, I create a local `install` block where Maven repo URL is redefined. Hope it is not too ugly ;-(

**Comment by rhuss** [comment]
done
